### ISSUE TITLE
[feature request] lower_bound like function for Map

### ISSUE THREAD

**Issue by redboltz** [ZLY201/js-sdsl#1]
Thank you for writing a great library.
I'm looking for https://stackoverflow.com/questions/65948823/sorted-ordered-collection-for-javascript

https://github.com/ZLY201/js-sdsl/blob/1ea84551eb7c7cf07cce5752406e18896f0c34ab/src/Map/Map.ts
seems to have the follwoing methods:

- size()
- empty()
- clear()
- front()
- back()
- forEach()
- getElementByPos()
- eraseElementByPos()
- eraseElementByKey()
- setElement()
- find()
- getElementByKey()
- union()
- getHeight()

I'd like to do as follows.
Let's say the Map has the key [1, 3, 6, 7] (values are not important so I omit them), and call some lower_bound() like function with the argument 4, then return node 6 because it is just after the 4.
I guess that I can't do that using a combination of existing methods.

**Comment by ZLY201** [comment]
Thank you for your suggestion. This is exactly what I plan to do next. The two methods `lower_bound` and `upper_bound` will be provided in the next version for Set and Map.

**Comment by redboltz** [comment]
Thank you!
I look forward to the next version!


By the way, do you have any plan to implement functions that return (external) iterator like C++ STL ?
I want to get the node not only the next of the not found key (lower_bound return value), but also the previous node.
The C++ code that demonstrates it:
https://wandbox.org/permlink/GNvIf5dFl8LLSUUm

**Comment by ZLY201** [comment]
Yes, This is indeed in my plan. Iterator is one of the three major components of C++ STL so it is necessary to implement it.

But unfortunately, of course you know there is no pointer in js, so it may be difficult to complete it in a short time. I may add iterator in v3.0.0 if possible.

The good news is that you can use `for...of` to iterate in v2.x. This may be helpful I think.

**Comment by redboltz** [comment]
Thank you for considering. 
I think that introducing iterator is big update too.

So far, I only need to lower_bound. Without iteration functionality, it is still very useful.

---

FYI collections.js has similer function:
http://www.collectionsjs.com/method/find-least-greater-than-or-equal

- upper_bound like
   - http://www.collectionsjs.com/method/find-least-greater-than
- lower_bound like
   - http://www.collectionsjs.com/method/find-least-greater-than-or-equal

NOTE: 
There are related functions:
http://www.collectionsjs.com/method/find-greatest-less-than
http://www.collectionsjs.com/method/find-greatest-less-than-or-equal

**Comment by ZLY201** [comment]
The new version v2.0.3 has being published.

Thank you again for your support!

**Comment by redboltz** [comment]
Thank you for quick implementation! I've tested it. It works fine.
I noticed the name is snake_case. It is natural for C++ STL user but other js-sdsl APIs are lowerCamelCase.
Is it intentional?
Perhaps `lowerBound` is natural for JS users.

**Comment by ZLY201** [comment]
OK. Function names will be standardized before the release of API documents.(soon)
